name:                gpx
version:             0.1.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- base >= 4.7 && < 5
- bytestring
- protolude
- text
- xeno

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -fno-ignore-asserts

executables:
  m:
    main: Main.hs
    source-dirs: app
    dependencies:
    - gpx

tests:
  tests-unit:
    source-dirs:         test
    main:                hspec.hs
    dependencies:
    - gpx
    - hspec
